# Generated by Django 4.0.5 on 2022-06-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='traveller',
            name='traveller',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Traveller',
        ),
    ]
